Repository ephios-dev/ephios, pull requests merged in 2020-09, with the labels that each got.

#99 add QualificationGrantFormset to UserProfileUpdateView
  ephios/settings.py
  ephios/static/ephios/js/main.js
  ephios/static/jquery/js/jquery.min.js
  ephios/templates/base.html
  ephios/user_management/forms.py
  ephios/user_management/templates/user_management/userprofile_form.html
  ephios/user_management/views.py
  poetry.lock
  pyproject.toml
Labels: [C] feature

#113 use concrete sender
  ephios/event_management/signals.py
Labels: [C] bug

#109 Pages plugin
  ephios/contrib/__init__.py
  ephios/contrib/signals.py
  ephios/helpers/context.py
  ephios/helpers/signals.py
  ephios/helpers/templatetags/rich_text.py
  ephios/plugins/__init__.py
  ephios/plugins/basesignup/__init__.py
  ephios/plugins/basesignup/signals.py
  ephios/plugins/basesignup/signup/__init__.py
  ephios/plugins/basesignup/signup/confirm.py
  ephios/plugins/basesignup/signup/instant.py
  ephios/plugins/basesignup/templates/basesignup/requestconfirm_signup/disposition.html
  ephios/plugins/basesignup/templates/basesignup/requestconfirm_signup/fragment_participant.html
  ephios/plugins/basesignup/templates/basesignup/requestconfirm_signup/fragment_state.html
  ephios/plugins/basesignup/templates/basesignup/signup_instant_state.html
  ephios/plugins/basesignup/urls.py
  ephios/plugins/pages/__init__.py
  ephios/plugins/pages/admin.py
  ephios/plugins/pages/migrations/0001_initial.py
  ephios/plugins/pages/migrations/__init__.py
  ephios/plugins/pages/models.py
  ephios/plugins/pages/signals.py
  ephios/plugins/pages/templates/pages/view_page.html
  ephios/plugins/pages/urls.py
  ephios/plugins/pages/views.py
  ephios/settings.py
  ephios/static/ephios/css/main.css
  ephios/templates/base.html
  ephios/urls.py
  poetry.lock
  pyproject.toml
  tests/user_management/test_views_auth.py
Labels: [C] feature, [P] major

#114 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: [C] infrastructure
