Repository ephios-dev/ephios, pull requests merged in 2021-05, with the labels that each got.

#454 Install plugin in CI
  .github/workflows/tests.yml
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/core/test_consequences.py
  tests/core/test_event_bulk_actions.py
  tests/core/test_event_copy.py
  tests/core/test_event_form.py
  tests/core/test_event_notifications.py
  tests/core/test_ical.py
  tests/core/test_log.py
  tests/core/test_models.py
  tests/core/test_notifications.py
  tests/core/test_pdf.py
  tests/core/test_plugins.py
  tests/core/test_setupdata.py
  tests/core/test_signup_methods.py
  tests/core/test_views_auth.py
  tests/core/test_views_event.py
  tests/core/test_views_group.py
  tests/core/test_views_pwa.py
  tests/core/test_views_settings.py
  tests/core/test_views_user_profile.py
  tests/core/test_views_userprofile.py
  tests/core/test_workinghours.py
  tests/extra/test_settings.py
  tests/plugins/basesignup/test_requestconfirm_signup.py
  tests/plugins/basesignup/test_sectionbased_signup.py
  tests/plugins/eventautoqualification/test_autoqualification.py
  tests/plugins/guests/test_guest_signup.py
Labels: [C] infrastructure, dependencies

#456 add maximum number of participants to section based signup
  ephios/plugins/basesignup/signup/section_based.py
  ephios/plugins/basesignup/templates/basesignup/section_based/configuration_form.html
  ephios/plugins/basesignup/templates/basesignup/section_based/fragment_state.html
Labels: [C] enhancement

#455 refactor staging inventory
  .github/ci/staging-inventory.yml
  .github/workflows/staging.yml
Labels: [C] infrastructure

#405 add calendar view for events
  ephios/core/calendar.py
  ephios/core/templates/core/event_calendar.html
  ephios/core/templates/core/event_list.html
  ephios/core/urls.py
  ephios/core/views/event.py
  ephios/static/ephios/css/main.css
  tests/core/test_event_bulk_actions.py
Labels: [C] feature

#458 fix staging inventory
  .github/workflows/staging.yml
Labels: [C] infrastructure

#460 fix inventory again
  .github/workflows/staging.yml
Labels: [C] infrastructure

#467 Staging: ansible pipelining
  .github/workflows/staging.yml
Labels: [C] infrastructure
