Repository ephios-dev/ephios, pull requests merged in 2021-01, with the labels that each got.

#246 update jquery to 3.5.1
  ephios/settings.py
  ephios/static/jquery/js/jquery-3.5.1.min.js
  ephios/templates/base.html
Labels: [C] security, dependencies

#258 reduce min min amount of section to 0
  ephios/plugins/basesignup/signup/section_based.py
Labels: [C] enhancement

#264 add documentation
  CONTRIBUTING.md
  README.md
  docs/Makefile
  docs/admin/index.rst
  docs/conf.py
  docs/development/contributing.rst
  docs/development/index.rst
  docs/development/plugin.rst
  docs/index.rst
  docs/locales/de_DE/LC_MESSAGES/admin.po
  docs/locales/de_DE/LC_MESSAGES/development.po
  docs/locales/de_DE/LC_MESSAGES/index.po
  docs/locales/de_DE/LC_MESSAGES/user.po
  docs/make.bat
  docs/user/index.rst
  poetry.lock
  pyproject.toml
Labels: [C] documentation
