Repository ephios-dev/ephios, pull requests merged in 2023-10, with the labels that each got.

#1087 dont clear names on missing oidc claims
  ephios/extra/auth.py
Labels: [C] bug

#972 add federation
  ephios/api/access/auth.py
  ephios/api/templates/api/access_token_list.html
  ephios/api/templates/oauth2_provider/application_list.html
  ephios/api/templates/oauth2_provider/authorize.html
  ephios/api/urls.py
  ephios/api/views/users.py
  ephios/core/context.py
  ephios/locale/de/LC_MESSAGES/django.po
  ephios/plugins/federation/__init__.py
  ephios/plugins/federation/admin.py
  ephios/plugins/federation/apps.py
  ephios/plugins/federation/forms.py
  ephios/plugins/federation/migrations/0001_initial.py
  ephios/plugins/federation/migrations/0002_federatedeventshare.py
  ephios/plugins/federation/migrations/0003_alter_federatedguest_access_token_and_more.py
  ephios/plugins/federation/migrations/__init__.py
  ephios/plugins/federation/models.py
  ephios/plugins/federation/serializers.py
  ephios/plugins/federation/signals.py
  ephios/plugins/federation/templates/federation/event_detail.html
  ephios/plugins/federation/templates/federation/external_event_list.html
  ephios/plugins/federation/templates/federation/federatedguest_confirm_delete.html
  ephios/plugins/federation/templates/federation/federatedhost_confirm_delete.html
  ephios/plugins/federation/templates/federation/federation_settings.html
  ephios/plugins/federation/templates/federation/invitecode_form.html
  ephios/plugins/federation/templates/federation/invitecode_reveal.html
  ephios/plugins/federation/templates/federation/redeem_invite_code.html
  ephios/plugins/federation/urls.py
  ephios/plugins/federation/views/api.py
  ephios/plugins/federation/views/frontend.py
  ephios/settings.py
  ephios/templates/base.html
  poetry.lock
  pyproject.toml
  tests/api/test_oauth_views.py
  tests/conftest.py
  tests/plugins/federation/conftest.py
  tests/plugins/federation/test_federation_setup.py
  tests/plugins/federation/test_federation_views.py
  tests/settings.py
Labels: [C] feature

#1088 customizable OIDC
  docs/admin/additional_features/oidc.rst
  ephios/core/admin.py
  ephios/core/dynamic_preferences_registry.py
  ephios/core/forms/users.py
  ephios/core/migrations/0022_identityprovider.py
  ephios/core/models/users.py
  ephios/core/templates/core/identityprovider_confirm_delete.html
  ephios/core/templates/core/identityprovider_discovery.html
  ephios/core/templates/core/identityprovider_form.html
  ephios/core/templates/core/identityprovider_list.html
  ephios/core/templatetags/settings_extras.py
  ephios/core/urls.py
  ephios/core/views/auth.py
  ephios/core/views/settings.py
  ephios/extra/auth.py
  ephios/settings.py
  ephios/templates/base.html
  ephios/templates/registration/login.html
  ephios/urls.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/core/test_auth.py
Labels: [C] feature

#1106 remove live_server and serialized_rollback from tests
  ephios/plugins/federation/templates/federation/external_event_list.html
  ephios/plugins/federation/views/api.py
  ephios/plugins/federation/views/frontend.py
  tests/conftest.py
  tests/plugins/federation/conftest.py
  tests/plugins/federation/test_federation_setup.py
  tests/plugins/federation/test_federation_views.py
  tests/settings.py
Labels: [C] infrastructure

#1112 introduce display_name for users
  ephios/api/views/users.py
  ephios/core/forms/users.py
  ephios/core/management/commands/devdata.py
  ephios/core/migrations/0023_remove_userprofile_first_name_and_more.py
  ephios/core/models/events.py
  ephios/core/models/users.py
  ephios/core/signup/disposition.py
  ephios/core/signup/methods.py
  ephios/core/signup/participants.py
  ephios/core/templates/core/settings/settings_personal_data.html
  ephios/core/templates/core/workinghours_list.html
  ephios/core/views/accounts.py
  ephios/core/views/auth.py
  ephios/core/views/workinghour.py
  ephios/core/widgets.py
  ephios/extra/auth.py
  ephios/plugins/basesignup/signup/common.py
  ephios/plugins/federation/migrations/0004_remove_federateduser_first_name_and_more.py
  ephios/plugins/federation/models.py
  ephios/plugins/federation/views/api.py
  ephios/plugins/guests/migrations/0005_alter_guestuser_unique_together_and_more.py
  ephios/plugins/guests/models.py
  ephios/plugins/guests/views.py
  ephios/static/plugins/basesignup/js/disposition.js
  tests/conftest.py
  tests/core/test_auth.py
  tests/core/test_models.py
  tests/core/test_views_userprofile.py
  tests/core/test_workinghours.py
  tests/plugins/basesignup/test_requestconfirm_signup.py
  tests/plugins/federation/conftest.py
  tests/plugins/guests/test_guest_signup.py
Labels: [C] enhancement

#1111 modellogging catch missing model errors
  ephios/modellogging/json.py
  ephios/modellogging/recorders.py
Labels: [C] bug

#1117 fix UserProfileSerializer and wrong FederatedHost.name
  ephios/api/views/users.py
  ephios/plugins/federation/forms.py
  tests/plugins/federation/test_federation_setup.py
Labels: [C] bug

#1119 Fix creating user with HR permissions
  ephios/core/forms/users.py
  tests/core/test_views_userprofile.py
Labels: [C] bug

#1115 assign users to groups from OIDC claims
  docs/admin/additional_features/oidc.rst
  ephios/core/dynamic_preferences_registry.py
  ephios/core/forms/users.py
  ephios/core/migrations/0024_identityprovider_create_missing_groups_and_more.py
  ephios/core/models/users.py
  ephios/core/templates/core/group_form.html
  ephios/core/templates/core/settings/settings_base.html
  ephios/core/templates/core/userprofile_form.html
  ephios/core/views/accounts.py
  ephios/core/views/auth.py
  ephios/extra/auth.py
  ephios/templates/registration/login.html
  tests/core/test_auth.py
Labels: [C] enhancement
