Repository ephios-dev/ephios, pull requests merged in 2023-01, with the labels that each got.

#852 fix simpleresource bugs
  ephios/plugins/simpleresource/forms.py
  ephios/plugins/simpleresource/signals.py
  tests/conftest.py
  tests/plugins/simpleresource/test_resources.py
Labels: [C] bug

#855 fix wrong media import for DjangoSelect2Widget
  ephios/plugins/simpleresource/forms.py
  ephios/plugins/simpleresource/models.py
Labels: [C] bug

#856 add selectable icon to simpleresource plugin
  ephios/plugins/simpleresource/forms.py
  ephios/plugins/simpleresource/migrations/0002_resourcecategory_icon.py
  ephios/plugins/simpleresource/models.py
  ephios/plugins/simpleresource/templates/simpleresource/resource_allocations.html
  ephios/plugins/simpleresource/templates/simpleresource/resourcecategories_form.html
Labels: [C] enhancement

#846 Event Filter
  .env.example
  ephios/core/forms/users.py
  ephios/core/models/events.py
  ephios/core/templates/core/event_archive.html
  ephios/core/templates/core/event_calendar.html
  ephios/core/templates/core/event_copy.html
  ephios/core/templates/core/event_list.html
  ephios/core/templates/core/fragments/shift_box_big.html
  ephios/core/templates/core/logentry_list.html
  ephios/core/templates/core/pagination.html
  ephios/core/templatetags/event_extras.py
  ephios/core/templatetags/param_replace.py
  ephios/core/urls.py
  ephios/core/views/event.py
  ephios/extra/management/commands/devdata.py
  ephios/extra/templatetags/ephios_crispy.py
  ephios/extra/templatetags/utils.py
  ephios/settings.py
  ephios/static/ephios/scss/ephios_custom.scss
  ephios/static/ephios/scss/ephios_utilities.scss
  ephios/static/ephios/scss/main.scss
  ephios/templates/base.html
  tests/conftest.py
  tests/core/test_event_calendar.py
  tests/core/test_event_detail.py
  tests/core/test_event_form.py
  tests/core/test_event_list.py
  tests/core/test_views_event.py
  tests/core/test_views_group.py
Labels: [C] feature

#859 Remove unused fields from special case signup methods
  ephios/plugins/basesignup/signup/common.py
  ephios/plugins/basesignup/signup/coupled_signup.py
  ephios/plugins/basesignup/signup/no_selfservice.py
  tests/plugins/basesignup/test_no_selfservice.py
Labels: [C] enhancement, python

#862 makemessages, translation and string fixes
  ephios/core/templates/core/event_list.html
  ephios/core/views/event.py
  ephios/locale/de/LC_MESSAGES/django.po
Labels: [C] translation

#868 fix no-self and coupled shift config forms
  ephios/plugins/basesignup/signup/coupled_signup.py
  ephios/plugins/basesignup/signup/no_selfservice.py
Labels: [C] bug, [P] major
