Repository ephios-dev/ephios, pull requests merged in 2024-10, with the labels that each got.

#1389 Fix blocks editor permission
  ephios/plugins/complexsignup/views.py
Labels: [C] bug

#1388 Fix teams structure fullness display
  ephios/core/signup/stats.py
  ephios/plugins/baseshiftstructures/structure/group_common.py
  ephios/plugins/baseshiftstructures/structure/named_teams.py
Labels: [C] bug

#1391 Add management command to fix mariadb UUID issues
  docs/admin/deployment/index.rst
  docs/development/contributing.rst
  ephios/core/management/commands/convert_mariadb_uuids.py
Labels: [C] documentation, [C] infrastructure

#1394 add guest as url param for shared events, switch schema generation to drf-spectacular
  docs/conf.py
  ephios/api/urls.py
  ephios/api/views/users.py
  ephios/plugins/federation/models.py
  ephios/plugins/federation/serializers.py
  ephios/plugins/federation/templates/federation/external_event_list.html
  ephios/plugins/federation/urls.py
  ephios/plugins/federation/views/api.py
  ephios/plugins/federation/views/frontend.py
  ephios/settings.py
  poetry.lock
  pyproject.toml
  tests/plugins/federation/test_federation_views.py
Labels: [C] bug

#1393 introduce DownloadTicket for files
  ephios/core/urls.py
  ephios/core/views/files.py
  ephios/extra/utils.py
  ephios/plugins/files/views.py
Labels: [C] bug

#1397 Refactor Media Download
  docs/admin/configuration/index.rst
  ephios/core/services/files.py
  ephios/core/urls.py
  ephios/core/views/files.py
  ephios/extra/middleware.py
  ephios/extra/mixins.py
  ephios/extra/utils.py
  ephios/plugins/files/views.py
  ephios/settings.py
Labels: [C] refactoring

#1398 ci: ensure migrations have been created
  .github/workflows/tests.yml
  ephios/plugins/federation/migrations/0005_alter_federatedeventshare_options_and_more.py
  ephios/settings.py
Labels: [C] infrastructure

#1405 Translation
  ephios/locale/de/LC_MESSAGES/django.po
Labels: [C] translation

#1408 fix subblock enumeration
  ephios/plugins/complexsignup/static/complexsignup/editor.js
  ephios/plugins/complexsignup/templates/complexsignup/vue_editor.html
  ephios/plugins/files/signals.py
  ephios/plugins/simpleresource/signals.py
Labels: [C] bug
