Repository ephios-dev/ephios, pull requests merged in 2025-01, with the labels that each got.

#1462 replace p with div
  ephios/modellogging/templates/modellogging/logentry_grouped_list.html
Labels: [C] bug

#1463 fix anonymous event detail call
  ephios/core/models/events.py
  ephios/templates/500.html
Labels: [C] bug

#1465 use argon2 as password hasher
  ephios/settings.py
  poetry.lock
  pyproject.toml
Labels: [C] security

#1466 encapsulate dynamic settings default prefix
  ephios/core/dynamic.py
  ephios/core/templatetags/settings_extras.py
Labels: [C] refactoring

#1479 add missing import for dynamic_settings
  ephios/plugins/federation/views/api.py
Labels: [C] bug
